default:
  before_script:
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - export PATH="$PATH:$HOME/.poetry/bin/"
    # - poetry config virtualenvs.create false
    - poetry config virtualenvs.in-project true # for caching
    - poetry install --no-interaction --no-ansi
  image: python:3.8
  cache:
    key: "${CI_PROJECT_ID}-${CI_COMMIT_REF_SLUG}-${CI_JOB_IMAGE}"
    paths:
      - .cache/pip
      - .venv

stages:
  - test

pytest_38: &pytest
  stage: test
  script: poetry run pytest -v --junit-xml=${CI_JOB_NAME}.xml --cov-report term --cov-report xml:cov_${CI_JOB_NAME}.xml --cov=gitlabtree
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: pytest*.xml
      coverage_report:
        coverage_format: cobertura
        path: cov_pytest*.xml

pytest_39: 
  <<: *pytest
  image: python:3.9

pytest_310:
  <<: *pytest
  image: python:3.10

black:
  stage: test
  script: poetry run black --check gitlabtree tests

mypy:
  stage: test
  script: poetry run mypy gitlabtree tests