[project]
name = "gitlabtree"
version = "0.1.3"
description = "CLI tool for gathering GitLab information in tree format"
authors = [{ name = "ubaumann", email = "github@m.ubaumann.ch" }, { name = "untersander", email = "github@untersander.dev"}]
requires-python = ">=3.11.0,<4"
readme = "README.md"
dependencies = [
    "typer>=0.19,<0.20",
    "rich>=14,<15",
    "requests>=2,<3",
    "pydantic~=2.0",
    "types-requests>=2,<3",
]

[project.scripts]
gitlabtree = "gitlabtree.main:app"

[dependency-groups]
dev = [
    "pytest>=8,<9",
    "black>=25,<26",
    "mypy>=1.18,<2",
    "pytest-cov>=7,<8",
    "pylint>=3,<4",
    "pygount>=3,<4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
python_version = "3.8"
plugins = "pydantic.mypy"
check_untyped_defs = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
ignore_errors = false
ignore_missing_imports = true
strict_optional = true
warn_unused_configs = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 88
disable = "R0903, W0511"
extension-pkg-whitelist = "pydantic"
